security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SONATA_ADMIN, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are not using acl then this line must be uncommented

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main_login:
            pattern: ^/login$
            anonymous: true
            
        main:
            pattern:      ^/
            anonymous:    false
            provider:     fos_userbundle
            form_login:
                login_path:     /login
                check_path:     /login_check
            logout:
                path:   /logout
                target: /
            remember_me:
                key:    %secret%

    access_control:
        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
