<?php

namespace SrtTags\VideosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceRepository extends EntityRepository
{
    public function getSequencesByTags(array $tags)
    {
        
        $qb = $this->createQueryBuilder('s');
        
        $qb->join('s.video', 'v')
           ->addSelect('v')
           ->join('s.tags', 't');
           
		$qb->where('t.tag = :tag');
		
		$qb->setParameter('tag', $tags[0]);
        
        return $qb->getQuery()
                  ->getArrayResult();
    }
}
