<?php

namespace SrtTags\VideosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceRepository extends EntityRepository
{
    public function getSequencesByTag($tag)
    {
        $query = $this->_em->createQuery('SELECT s.start, s.stop, v.title, v.path
                                          FROM SrtTagsVideosBundle:Sequence s
                                          JOIN s.video v
                                          JOIN s.tags t
                                          WHERE t.tag = :tag');
        $query->setParameter('tag', $tag);
        $resultats = $query->getResult();
        
        return $resultats;
    }
}
