<?php

namespace SrtTags\VideosBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SrtFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SrtFileRepository extends EntityRepository
{
	public function getSrtFiles($nbrParPage, $page)
	{
		if ($page < 1) {
			throw new \InvalidArgumentException('L\'argument $page ne peut pas être inférieur à 1.');
		}
		
		$query = $this->_em->createQuery('SELECT s FROM SrtTagsVideosBundle:SrtFile s');
		
		$query->setFirstResult(($page-1) * $nbrParPage)
		      ->setMaxResults($nbrParPage);
		      
		return new Paginator($query);
	}
}
