<?php

namespace SrtTags\VideosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function listTags($tag)
    {
        $query = $this->_em->createQuery('SELECT t FROM SrtTagsVideosBundle:Tag t WHERE t.tag LIKE :tag');
        $query->setParameter('tag', '%'.$tag.'%');
        $resultats = $query->getResult();
        
        return $resultats;
    }
}
