<?php

namespace SrtTags\VideosBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * VideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoRepository extends EntityRepository
{
	public function getVideos($nbrParPage, $page)
	{
		if ($page < 1) {
			throw new \InvalidArgumentException('L\'argument $page ne peut pas être inférieur à 1.');
		}
		
		$query = $this->_em->createQuery('SELECT v FROM SrtTagsVideosBundle:Video v');
		
		$query->setFirstResult(($page-1) * $nbrParPage)
		      ->setMaxResults($nbrParPage);
		      
		return new Paginator($query);
	}
}
